### ISSUE TITLE
Core data multithreading violation on transaction.create()

### ISSUE THREAD

**Issue by Conrad-m-wise** [JohnEstropia/CoreStore#60] opened 2016-04-14 10:40 UTC
I have this launch option set for my development scheme "-com.apple.CoreData.ConcurrencyDebug 1"  to catch core data multi threading violations. 

I am trying to create an object from a beginAsynchronous block but the app crashes 

dataStack.beginAsynchronous { (transaction) in
            
            Delete any saved message with same id
            let int = transaction.deleteAll(From(ManagedUserMessage), Where("messageID", isEqualTo:message.messageID))
            
            if int > 0{
                log.debug("Did delete user message with ID:\(message.messageID)")
            }
            
            //Create new message
            let managedMessage = transaction.create(Into(ManagedUserMessage)) 
}

if i remove the launch option it does not fail.

**Comment by JohnEstropia** [comment] 2016-04-14 13:02
@Conrad-m-wise Hi, this is a duplicate of https://github.com/JohnEstropia/CoreStore/issues/28.

As I mentioned on that thread, 
> The `com.apple.CoreData.ConcurrencyDebug` flag lets Core Data tell you when the managed context is accessed from any queue other than its own, which includes CoreStore's transactions' queues (`beginAsynchronous()`, etc).

> CoreStore already guarantees safety for you by making the Main Context read-only, and by only allowing updates to be made within transactions. You should be safe even without the ConcurrencyDebug flag (as long as you don't do hacky things).

Let me know if you need any clarifications :)

**Closed** 2016-04-14 13:03 UTC
Labels: wontfix
