### ISSUE TITLE
context.parentStack == nil

### ISSUE THREAD

**Issue by MaxPaymon** [JohnEstropia/CoreStore#281] opened 2018-10-26 06:52 UTC
Hi. 
I found that in some cases in row
`fetchRequest.entity = context.parentStack!.entityDescription(for: EntityIdentifier(self.entityClass))!`
context.parentStack can be nil. But i dont understand why?
Can you help me?

This From.swift : 144

**Comment by MaxPaymon** [comment] 2018-10-29 09:52
<img width="1344" alt="2018-10-29 14 51 50" src="https://user-images.githubusercontent.com/29461219/47642350-44244e80-db8a-11e8-879f-ffa64edcb1cd.png">

**Comment by JohnEstropia** [comment] 2018-11-03 00:36
@MaxPaymon Hi, can you show the code how it's being used in your app?

**Comment by JohnEstropia** [comment] 2018-11-03 00:37
This may also happen if the `DataStack` is deallocated before the objects are accessed. Is your `DataStack` properly retained somewhere?

**Comment by clouddevil** [comment] 2018-11-27 16:09
It happens if DataStack setupped for managed model but fetch dynamic object.

But i have another issue with early-deallocated fetched objects.

Please, can you see 
https://github.com/clouddevil/CoreStore/blob/6859babd5c63b5dcd9d18034291d174db681c105/CoreStoreTests/IssueTests.swift#L53

and some tests for legacy storage are broken...

**Comment by JohnEstropia** [comment] 2018-11-28 09:22
@MaxPaymon Is your case just as @clouddevil stated above? If so then this is by design and I'd close this issue

**Comment by MaxPaymon** [comment] 2018-11-28 09:55
> Null pointer dereference is reproduced when fetching Dynamic Object from DataStack set up for managed model (NSManagedObject).

Hi!. Do not quite understand what to do in this case.

**Comment by MaxPaymon** [comment] 2018-11-28 09:58
> This may also happen if the `DataStack` is deallocated before the objects are accessed. Is your `DataStack` properly retained somewhere?

I call Data Stack initialization when user is authorized. I do this so that each user has his own database

<img width="798" alt="2018-11-28 14 57 27" src="https://user-images.githubusercontent.com/29461219/49144003-19125380-f31e-11e8-91f2-ec1a9b03af8c.png">

**Comment by clouddevil** [comment] 2018-11-28 10:12
I have the same error when fetch DO object. Sample:
https://github.com/clouddevil/CoreStore/blob/6859babd5c63b5dcd9d18034291d174db681c105/CoreStoreTests/IssueTests.swift#L60

i fix https://github.com/JohnEstropia/CoreStore/issues/290, @JohnEstropia thank you

**Comment by MaxPaymon** [comment] 2018-11-28 12:43
I get it what you mean, but I am faced with the problem of implementation
<img width="883" alt="2018-11-28 17 40 47" src="https://user-images.githubusercontent.com/29461219/49152501-db6cf500-f334-11e8-82a1-b4051b88ad76.png">

**Comment by clouddevil** [comment] 2018-11-28 13:10
I am sure, It will be easier to answer, if you show the code sample how storage is being used in your app.

**Comment by MaxPaymon** [comment] 2018-11-28 14:12
<img width="549" alt="2018-11-28 19 11 34" src="https://user-images.githubusercontent.com/29461219/49157373-78358f80-f341-11e8-93d4-4d8a211ad494.png">
<img width="618" alt="2018-11-28 19 11 44" src="https://user-images.githubusercontent.com/29461219/49157375-78ce2600-f341-11e8-90e2-f55f13571c71.png">

**Comment by JohnEstropia** [comment] 2018-11-29 04:17
@MaxPaymon In your `CacheManager` class, you need to retain a strong reference to the `DataStack`, not the `LocalStorage`

**Comment by MaxPaymon** [comment] 2018-11-29 11:04
How can i do it?

**Comment by clouddevil** [comment] 2018-11-29 13:15
I try to reproduce the issue, and might be wrong.
See:
https://github.com/clouddevil/CoreStore/blob/c413290adca898891c89bd445d9665d29a6a581d/CoreStoreTests/IssueTests.swift#L86
Is fetched object from different object model?  

Some another question:
If has only one "Default" configuration, it must be set to nil ? 
How to link application with CoreStore as static library?   (without use_frameworks! in pod)

**Comment by MaxPaymon** [comment] 2018-11-29 13:20
I just need to create a separate database for each user
The application throws an error when I initialize the Storage with another name.

**Comment by clouddevil** [comment] 2018-11-29 13:33
CoreStore.defaultStack is singleton. Did you rewrite stack with last one?

**Comment by MaxPaymon** [comment] 2018-11-29 13:39
Yes

**Comment by JohnEstropia** [comment] 2018-12-05 10:02
If you require a separate store for each user, don't use `CoreStore.defaultStack`.
In your `CacheManager`, replace
```swift
private var storage: LocalStorage?
```
with
```swift
private var dataStack: DataStack?
```

and assign your `DataStack` there.

I'm closing this ticket as it seems to be an app-specific implementation issue. I would encourage for you to understand the relationships between DataStacks and LocalStorages, see https://github.com/JohnEstropia/CoreStore#architecture )

**Closed by JohnEstropia** 2018-12-05 10:02 UTC

**Comment by MaxPaymon** [comment] 2019-01-10 06:57
Здравствуйте! Я сделал, как вы советовали, но проблема осталось такой же.
<img width="1072" alt="2019-01-10 11 46 15" src="https://user-images.githubusercontent.com/29461219/50951315-8218e980-14ce-11e9-8596-5aaa67972e91.png">

The initDB function is called every time I log in as a user.

The error occurs only when I log out from the account of one user and immediately try to log in to another user.

The place where the error most likely occurs
<img width="462" alt="2019-01-10 11 52 02" src="https://user-images.githubusercontent.com/29461219/50951405-e3d95380-14ce-11e9-94c9-b71e170c2b10.png">
