### ISSUE TITLE
Xcode 9, Swift 4 compile time errors.

### ISSUE THREAD

**Issue by Vinit1993** [JohnEstropia/CoreStore#226] opened 2017-11-22 06:17 UTC
Hello,

I added CoreStore 4.2.4 framework to project and got errors mentioned in screen shot.

![screen shot 2017-11-22 at 11 26 21 am](https://user-images.githubusercontent.com/30582884/33112741-c3f0f900-cf7a-11e7-9cbc-faa05ad2d7b2.png)

Can someone help me on this?

**Comment by JohnEstropia** [comment] 2017-11-22 06:27
CoreStore 4.2.x is built for Swift 3.2. I'm closing this as duplicate of https://github.com/JohnEstropia/CoreStore/issues/225#issuecomment-345896692
> Is your app on Swift 3.2 or Swift 4.0?
> 
> If on Swift 3.2:
> pod 'CoreStore', '~> 4.2'
> 
> If on Swift 4.0:
> pod 'CoreStore', :git => 'https://github.com/JohnEstropia/CoreStore.git', :branch => 'prototype/Swift_4_0'

**Closed by JohnEstropia** 2017-11-22 06:27 UTC

**Comment by Vinit1993** [comment] 2017-11-22 07:30
Thanks John for immediate reply. The problem which I was facing is fixed
now.
