### ISSUE TITLE
Crash when list monitor refetch is called

### ISSUE THREAD

**Issue by laeroah** [JohnEstropia/CoreStore#110] opened 2016-10-09 15:26 UTC
I'm getting a crash when I call `refetch` on a `ListMonitor`. This crash is 100% reproducible. 

<img width="812" alt="screen shot 2016-10-09 at 11 01 49 am" src="https://cloud.githubusercontent.com/assets/1928509/19221355/ec973304-8e0f-11e6-85da-1d63289ae580.png">

**Comment by JohnEstropia** [comment] 2016-10-10 02:56
Were you calling `refetch` before [this fix](https://github.com/JohnEstropia/CoreStore/issues/100) was added?

**Comment by laeroah** [comment] 2016-10-10 03:32
I m using the develop branch. I guess the fix wasn't merged yet. Sry, I will override this. 
Any plan on fixing this problem in the main branch?

**Comment by JohnEstropia** [comment] 2016-10-10 03:42
Sorry, that's not what I mean. The fix is already in the master branch, but I wanted to know if you have the same problem before the fix was added.

**Comment by JohnEstropia** [comment] 2016-10-10 03:44
The demo app's "Colors" demo doesn't encounter this problem though... hmm

**Comment by laeroah** [comment] 2016-10-10 03:45
hmm, I think so. I was using the master branch tag 2.1.2, but it was crashing. I just changed the CoreStoreBridge.m implementation of `affectedStores` to exactly like you did in the fix, and it stopped crashing.

```
- (NSArray<NSPersistentStore *> *)affectedStores {
    
    // Bugfix for NSFetchRequest messing up memory management for `affectedStores`
    // http://stackoverflow.com/questions/14396375/nsfetchedresultscontroller-crashes-in-ios-6-if-affectedstores-is-specified
    CFBridgingRetain([super affectedStores]);
    return [super affectedStores];
}
```

**Comment by laeroah** [comment] 2016-10-10 03:45
does the demo app us sectioned list?

**Comment by JohnEstropia** [comment] 2016-10-10 03:47
>  I just changed the CoreStoreBridge.m implementation of affectedStores to exactly like you did in the fix, and it stopped crashing.

That's not the latest fix. That one still breaks on some other case (sorry I forgot).
The latest fix is the one in the master branch: https://github.com/JohnEstropia/CoreStore/blob/master/Sources/ObjectiveC/CoreStoreBridge.m

> does the demo app use sectioned list?

Yes

**Comment by laeroah** [comment] 2016-10-10 03:48
ok, so I did have the latest master. I just double checked, and it does crash. Let me take a look at the demo app.

**Comment by JohnEstropia** [comment] 2016-10-10 04:38
Thanks. The cause is the same ARC bug, but it would be great help if you can isolate the conditions to reproduce so we can tweak the workaround without breaking other cases.

**Comment by JohnEstropia** [comment] 2016-10-25 22:44
@laeroah Hi, have you resolved this issue? I haven't encountered this problem on my side in 2 apps I use sectioned monitors in..

**Comment by laeroah** [comment] 2016-10-26 15:48
Hey, thanks for checking. It looks fine now. Not crashing anymore!

**Comment by JohnEstropia** [comment] 2016-10-27 07:04
Thanks for the update :) Closing this issue now

**Closed by JohnEstropia** 2016-10-27 07:04 UTC

**Comment by laeroah** [comment] 2017-04-03 05:08
hi, looks like this problem is back. I'm getting consistent crash when I try to refetch.

**Comment by JohnEstropia** [comment] 2017-04-03 09:45
@laeroah I'm not sure there were any changes there. Have you changed CoreStore versions or Xcode versions recently?

**Comment by laeroah** [comment] 2017-04-03 13:49
I m on CoreStore 8.10. xcode8.3.
I think this issue's been there for a while. I was pointing to my fork
without the code which causes the crash before.
