### ISSUE TITLE
Strange behaviour ListMonitor in Xcode 12b5

### ISSUE THREAD

**Issue by iEdward** [JohnEstropia/CoreStore#400] opened 2020-08-26 14:53 UTC
Hi! I'am use ListMonitor in my project. In Xcode 11 when I create ListMonitor,  it loads all object from database. In Xcode 12 it ignored existing objects and load only new created.

I create demo project to illustrate this
https://github.com/iEdward/CoreStoreListMonitor_Test

**Comment by JohnEstropia** [comment] 2020-08-28 00:51
I'll take a look

**Comment by JohnEstropia** [comment] 2020-08-28 03:28
@iEdward Thanks for the report.
Yeah this is weird. Can you reproduce it on any device?

It seems to be a simulator bug because I can't reproduce it on my iOS 13 iPhone.
It doesn't seem to be an `NSFetchedResultsController` issue as well after trying out a plain `NSFetchedResultsController` on iOS 14 simulator.

The demo apps seem to work properly as well 🤔

**Comment by iEdward** [comment] 2020-08-28 07:03
It reproduced on my device - 
iOS 14.0 (18A5357e)
Model: iPhone X (Model A1865, A1901, A1902, A1903)

In Xcode 12b6 still reproduce.

My application build in Xcode 11 and downloaded from TestFlight works fine on iOS 14. If I build it in Xcode 12 - stop working.

**Comment by JohnEstropia** [comment] 2020-08-28 07:21
Thanks, so I guess this is an iOS 14 issue.
I'll try to investigate further

**Comment by JohnEstropia** [comment] 2020-08-28 14:10
Submitted to Feedback Assistant for now (FB8563134). Hope they take a look ASAP

**Comment by skytoup** [comment] 2020-09-06 04:51
I'm in a similar situation, using `ListPublisher` in iOS14 I can't fetch the data, but the same query statement to fetch the quantity is normal. After a round of testing, it was confirmed that the `fetchBatchSize` property was set to cause the problem, and a developer has reported back to Apple!

`https://developer.apple.com/forums/thread/658717`

**Comment by JohnEstropia** [comment] 2020-09-06 04:53
@skytoup Thanks for the info! I'll take a look and see if we can find a temporary workaround within CoreStore 👍

**Comment by JohnEstropia** [comment] 2020-09-06 05:00
Oops, It sounds like they fixed it on beta 7. I'll confirm

**Comment by JohnEstropia** [comment] 2020-09-19 06:43
This should be fixed in the GM release so I'm marking this as resolved. If you are still having issues please submit a bug report to Apple

**Closed by JohnEstropia** 2020-09-19 06:43 UTC
Labels: investigating
